### ISSUE TITLE
Python: Unable to run (Windows 7, 8, 8.1 and various Linux distros)

### ISSUE THREAD

**Issue by prgnb** [rgbkrk/atom-script#539]
Apparently unable to find PATH variables by itself (no matter if started via command line or launcher). Output is

"Unable to run
python
Is it in your PATH?

PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

Other packages (i.e. atom-runner) work flawlessly.

**Comment by BramVanroy** [comment]
The same thing happens in Windows 10, as noted [here](https://github.com/rgbkrk/atom-script/issues/527). A "solution", or rather work around, that has been proposed there is to install the atom-terminal package. Does that solve the issue for you?

**Comment by prgnb** [comment]
I already tried that but this didn't work (and it does not still).

**Comment by Abimael08** [comment]
My output is also the same.

"Unable to run
python
Is it in your PATH?

PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

Is there not anyway at all to fix this issue? Currently starting to learn python and would love to have application fully functional

**Comment by Shuvomoy** [comment]
I can confirm this, installing atom-terminal package does not resolve the issue on Windows 8.

**Comment by technomorgue** [comment]
I was facing this issue on both Linux (Mint 17) and Windows 7. It was resolved on installing atom-terminal.

**Comment by jimmyDunne** [comment]
Having same issue here (ubuntu 14.04). Python can be called in my terminal without issue, Atom cannot seem to find it. Installed atom-terminal without any change.

**Comment by codekraft-studio** [comment]
in windows 7 too..

Unable to run

python
Is it in your PATH?

PATH: C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;

if I start it from atom.cmd or app-1.x.x\atom.exe

**Comment by Charrod** [comment]
Windows 10 also unable to run python.

**Comment by stevenlee87** [comment]
Windows 7 also unable to run python and installed atom-terminal package does not resolve the issue on Windows 7.

**Comment by techdiary** [comment]
On my Windows7, I found it easy and straight and i hope this might help you.
In Python Executable Path type C:\Python27\python.exe
